"""Plant-scoped Companion IssueStack and proposal authority."""

from .contracts import (
    ApprovedGovernanceSummaryV1,
    AttentionStatus,
    CloseCompanionIssueCommandV1,
    CompanionDecisionResultV1,
    CompanionGovernanceError,
    CompanionGovernanceErrorCode,
    CompanionGovernanceValidationError,
    CompanionIssueCloseResultV1,
    CompanionIssueDetailV1,
    DecideCompanionProposalCommandV1,
    DecisionValue,
    IssueStackPageV1,
    IssueStatus,
    PersistCompanionProposalCommandV1,
    ProposalEffect,
    ProposalPersistenceResultV1,
    ProposalState,
    SuggestedResolution,
)
from .models import (
    CompanionHumanAttention,
    CompanionIssue,
    CompanionProposal,
    DecisionRecord,
)
from .repository import CompanionGovernanceRepository, CurrentGovernanceScope
from .service import CompanionGovernanceService
from .runtime_contracts import (
    COMPANION_DEFINITION_V1,
    CompanionAgentDefinitionV1,
    CompanionInputRecordV1,
    CompanionModelResultV1,
    CompanionProviderRequestV1,
    CompanionRunCommandV1,
    CompanionRunResultV1,
    CompanionRuntimeValidationError,
)
from .runtime import (
    CompanionModelExecutor,
    CompanionRuntimeService,
    DatabaseCompanionInputAssembler,
    companion_run_fingerprint,
)

__all__ = [
    "ApprovedGovernanceSummaryV1",
    "AttentionStatus",
    "CloseCompanionIssueCommandV1",
    "CompanionDecisionResultV1",
    "CompanionGovernanceError",
    "CompanionGovernanceErrorCode",
    "CompanionGovernanceRepository",
    "CompanionGovernanceService",
    "CompanionGovernanceValidationError",
    "CompanionAgentDefinitionV1",
    "CompanionInputRecordV1",
    "CompanionModelExecutor",
    "CompanionModelResultV1",
    "CompanionProviderRequestV1",
    "CompanionRunCommandV1",
    "CompanionRunResultV1",
    "CompanionRuntimeService",
    "CompanionRuntimeValidationError",
    "CompanionHumanAttention",
    "CompanionIssue",
    "CompanionIssueCloseResultV1",
    "CompanionIssueDetailV1",
    "CompanionProposal",
    "CurrentGovernanceScope",
    "DatabaseCompanionInputAssembler",
    "DecisionRecord",
    "DecideCompanionProposalCommandV1",
    "DecisionValue",
    "IssueStackPageV1",
    "IssueStatus",
    "PersistCompanionProposalCommandV1",
    "ProposalEffect",
    "ProposalPersistenceResultV1",
    "ProposalState",
    "SuggestedResolution",
    "COMPANION_DEFINITION_V1",
    "companion_run_fingerprint",
]
